# Generated by Django 3.1 on 2022-01-09 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210512_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ivault_t_options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(db_column='grp', max_length=128)),
                ('definition', models.CharField(db_column='def1', max_length=128)),
                ('groupSort', models.SmallIntegerField(blank=1, db_column='grp_srt', null=1)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ivault_t_search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.FileField(db_column='f_name', max_length=128, upload_to='iVault2/media/')),
                ('search_string', models.CharField(db_column='s_string', default='Empty search string.', max_length=256)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('effectDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ivault_t_values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.FileField(db_column='f_name', max_length=128, upload_to='iVault2/media/')),
                ('optId', models.PositiveIntegerField(blank=True, db_column='opt_id', null=True)),
                ('selected', models.CharField(db_column='selected', default='Empty search string.', max_length=10)),
                ('option_group', models.CharField(db_column='option_group', default='Empty search string.', max_length=256)),
                ('option_text', models.CharField(db_column='option_text', default='Empty search string.', max_length=256)),
                ('resolution', models.CharField(db_column='resolution', default='Empty search string.', max_length=100)),
                ('effectDate', models.DateTimeField(auto_now_add=True, db_column='effect_date', null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
