# Generated by Django 3.1 on 2022-01-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ivault_t_options_ivault_t_search_ivault_t_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivault_t_values',
            name='effectDate',
            field=models.DateField(auto_now_add=True, db_column='effect_date', null=True),
        ),
    ]
