# Generated by Django 3.1 on 2022-01-09 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220109_2332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ivault_t_values',
            new_name='ivault_t_vals',
        ),
    ]
