# Generated by Django 3.1 on 2022-01-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220109_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivault_t_search',
            name='search_string',
            field=models.CharField(db_column='s_string', default='Empty search string.', max_length=512),
        ),
    ]
