# Generated by Django 3.1 on 2022-01-17 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220109_2337'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ivault_t_options',
            table='ivault_t_options',
        ),
        migrations.AlterModelTable(
            name='ivault_t_search',
            table='ivault_t_search',
        ),
        migrations.AlterModelTable(
            name='ivault_t_vals',
            table='ivault_t_vals',
        ),
    ]
