# Generated by Django 3.1 on 2022-01-20 00:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220117_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivault_t_search',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
