# Generated by Django 3.1 on 2022-02-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220120_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivault_t_search',
            name='fileName',
            field=models.CharField(db_column='f_name', max_length=128),
        ),
    ]
