# Generated by Django 3.1 on 2022-02-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220214_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivault_t_vals',
            name='fileName',
            field=models.CharField(db_column='f_name', max_length=128),
        ),
    ]
