# Generated by Django 3.1 on 2022-05-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220214_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTagHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetId', models.PositiveIntegerField()),
                ('alteredOptionId', models.PositiveIntegerField()),
                ('actionTaken', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(db_column='ts', default=models.DateTimeField(auto_now_add=True), editable=False)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='asset',
            name='categories',
        ),
        migrations.AlterField(
            model_name='asset',
            name='timestamp',
            field=models.DateTimeField(default=models.DateTimeField(auto_now_add=True), editable=False),
        ),
        migrations.AlterField(
            model_name='ivault_t_search',
            name='timestamp',
            field=models.DateTimeField(default=models.DateTimeField(auto_now_add=True), editable=False, null=True),
        ),
    ]
