# Generated by Django 3.1 on 2023-01-16 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220513_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='effectDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=0, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='batchtaghistory',
            name='timestamp',
            field=models.DateTimeField(db_column='ts', default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='ivault_t_search',
            name='effectDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=0, null=True),
        ),
        migrations.AlterField(
            model_name='ivault_t_search',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ivault_t_vals',
            name='effectDate',
            field=models.DateField(blank=True, db_column='effect_date', default=django.utils.timezone.now, editable=0, null=True),
        ),
    ]