# Generated by Django 3.1 on 2022-09-27 00:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_column='ts', default=django.utils.timezone.now, editable=False)),
                ('state', models.IntegerField()),
                ('asset_ids', models.JSONField(db_column='asset_ids')),
                ('oids_added', models.JSONField(db_column='oids_added')),
                ('oids_removed', models.JSONField(db_column='oids_removed')),
                ('username', models.CharField(blank=True, db_column='username', default='', max_length=64)),
            ],
        ),
    ]
