# Generated by Django 3.1 on 2023-03-09 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AltTextTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_column='path', default='Empty path string.', max_length=256)),
                ('requiredIds', models.JSONField(db_column='required_ids')),
                ('isRecursive', models.BooleanField(db_column='recursive', default=False)),
                ('template', models.CharField(db_column='template', default='Empty template data.', max_length=500)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
