# Generated by Django 3.1 on 2023-04-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altTextBot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alttexttemplate',
            name='grpHeader',
            field=models.CharField(db_column='grp_header', default='none', max_length=128),
        ),
    ]
