# Generated by Django 3.1 on 2023-04-19 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('altTextBot', '0002_alttexttemplate_grpheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltTextCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetId', models.PositiveIntegerField()),
                ('fileName', models.CharField(default='Empty fileName.', max_length=64)),
                ('path', models.CharField(default='Empty path string.', max_length=256)),
                ('altText', models.CharField(default='Empty altText.', max_length=500)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
