# Generated by Django 3.1 on 2023-04-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altTextBot', '0003_alttextcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='alttextcache',
            name='templateId',
            field=models.PositiveIntegerField(default='999'),
        ),
    ]
