# Generated by Django 3.1.7 on 2021-06-09 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagBotModes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=16)),
                ('description', models.CharField(blank=1, max_length=128, null=1)),
            ],
        ),
        migrations.CreateModel(
            name='TagBotMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='code', max_length=16)),
                ('optionIdsArray', models.CharField(max_length=128)),
                ('groupName', models.CharField(blank=1, max_length=64, null=1)),
                ('definition', models.CharField(blank=1, max_length=64, null=1)),
                ('logic', models.CharField(blank=1, max_length=256, null=1)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagBot.tagbotmodes')),
            ],
        ),
    ]
