# Generated by Django 3.1.7 on 2021-06-09 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagBot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagbotmapping',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='tagbotmapping',
            name='groupName',
        ),
    ]
