# Generated by Django 3.1.7 on 2021-06-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagBot', '0002_auto_20210609_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagbotmapping',
            name='optionIdsArray',
        ),
        migrations.AddField(
            model_name='tagbotmapping',
            name='optionIds',
            field=models.CharField(db_column='option_ids', default='EMPTY', max_length=128),
        ),
        migrations.AlterField(
            model_name='tagbotmapping',
            name='logic',
            field=models.CharField(blank=1, default='EMPTY', max_length=256),
        ),
    ]
