# Generated by Django 3.1.7 on 2021-05-28 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iv_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ivaultuser',
            name='date_of_birth',
        ),
    ]
