# Generated by Django 3.1.7 on 2021-03-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(db_column='name', max_length=128)),
                ('description', models.CharField(db_column='descr', max_length=128)),
                ('data', models.JSONField()),
                ('sort', models.SmallIntegerField(blank=1, db_column='sort', null=1)),
            ],
        ),
    ]
