# Generated by Django 3.1.7 on 2021-04-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchTemplates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchtemplate',
            old_name='description',
            new_name='descr',
        ),
        migrations.RenameField(
            model_name='searchtemplate',
            old_name='Name',
            new_name='name',
        ),
    ]
