# Generated by Django 3.1 on 2021-08-17 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchTemplates', '0002_auto_20210406_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchtemplate',
            name='data',
        ),
    ]
