# Generated by Django 3.1 on 2021-09-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchTemplates', '0003_remove_searchtemplate_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchtemplate',
            name='data',
            field=models.JSONField(default='2021-07-16 18:48:12.753135'),
            preserve_default=False,
        ),
    ]
