# Generated by Django 3.1 on 2022-12-28 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_auto_20221210_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterGroupItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(db_column='name', max_length=128)),
                ('Description', models.CharField(db_column='descr', max_length=128)),
                ('Sort', models.SmallIntegerField(blank=True, db_column='sort', null=True)),
                ('coreOption', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.option')),
            ],
        ),
        migrations.CreateModel(
            name='FilterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(db_column='name', max_length=128)),
                ('Description', models.CharField(db_column='descr', max_length=128)),
                ('Sort', models.SmallIntegerField(blank=True, db_column='sort', null=True)),
                ('filterGroupItems', models.ManyToManyField(to='assetFilterAdmin.FilterGroupItem')),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(db_column='name', max_length=128)),
                ('mach_name', models.CharField(db_column='mach_name', max_length=128)),
                ('LocationPath', models.CharField(db_column='loc_path', max_length=256)),
                ('Description', models.CharField(db_column='descr', max_length=128)),
                ('Sort', models.SmallIntegerField(blank=True, db_column='sort', null=True)),
                ('Enabled', models.BooleanField(db_column='enabled', default=True)),
                ('filterGroups', models.ManyToManyField(to='assetFilterAdmin.FilterGroup')),
            ],
        ),
    ]
