# Generated by Django 3.1 on 2022-12-30 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetFilterAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtergroup',
            name='parentFilter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assetFilterAdmin.filter'),
        ),
    ]
