# Generated by Django 3.1 on 2022-12-30 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetFilterAdmin', '0002_filtergroup_parentfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtergroupitem',
            name='parentGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assetFilterAdmin.filtergroup'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='Sort',
            field=models.SmallIntegerField(db_column='sort', default=0),
        ),
        migrations.AlterField(
            model_name='filtergroup',
            name='Sort',
            field=models.SmallIntegerField(db_column='sort', default=0),
        ),
        migrations.AlterField(
            model_name='filtergroupitem',
            name='Sort',
            field=models.SmallIntegerField(db_column='sort', default=0),
        ),
    ]
