# Generated by Django 3.1 on 2023-01-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetFilterAdmin', '0004_auto_20221230_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtergroup',
            name='Description',
            field=models.CharField(blank=True, db_column='descr', max_length=128, null=True),
        ),
    ]
