# Generated by Django 3.1 on 2023-01-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetFilterAdmin', '0005_auto_20230105_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='Description',
            field=models.CharField(blank=True, db_column='descr', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='filtergroupitem',
            name='Description',
            field=models.CharField(blank=True, db_column='descr', max_length=128, null=True),
        ),
    ]
