# Generated by Django 3.1.7 on 2021-05-12 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ivault_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_user', models.CharField(db_column='logged_user', default='no logged_user', max_length=64)),
                ('data', models.CharField(db_column='data', default='Empty log data.', max_length=256)),
                ('timestamp', models.DateTimeField(db_column='ts', default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
