# Generated by Django 3.1.7 on 2021-05-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iv_logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivault_logs',
            name='logged_user',
            field=models.CharField(blank=True, db_column='logged_user', default='no logged_user', max_length=64),
        ),
    ]
