# Generated by Django 3.1.7 on 2021-05-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iv_logger', '0002_auto_20210512_2129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ivault_logs',
            new_name='IvaultLogs',
        ),
    ]
