# Generated by Django 3.1.7 on 2021-05-12 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iv_logger', '0003_auto_20210512_2148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IvaultLogs',
            new_name='IvaultLog',
        ),
    ]
