# Generated by Django 3.1 on 2022-02-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iv_logger', '0005_auto_20210514_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='ivaultlog',
            name='filename',
            field=models.CharField(blank=True, db_column='filename', default='empty', max_length=128),
        ),
    ]
