# Generated by Django 3.1 on 2022-02-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iv_logger', '0007_auto_20220223_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='ivaultlog',
            name='mode',
            field=models.CharField(blank=True, db_column='mode', default='default', max_length=32),
        ),
    ]
