# Generated by Django 3.1 on 2022-03-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iv_logger', '0008_ivaultlog_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivaultlog',
            name='data',
            field=models.CharField(db_column='data', default='Empty log data.', max_length=2500),
        ),
    ]
